.storybook/middleware.js, package.json, src/AppRouter.tsx, src/containers/main/MainContainer.tsx, src/core/auth/AuthGuard.tsx, src/core/auth/UserContext.tsx, src/locales/en/messages.po, src/locales/fa/messages.po, src/pages/auth/AuthPage.tsx, src/pages/auth/Login.tsx, src/pages/auth/LoginForm.tsx, src/pages/full-page-error/FullPageError.tsx, src/pages/loading/FullPageSpinner.tsx, src/relay/fetchQuery.ts, src/shared/error-boundary/ErrorBoundary.tsx, src/shared/error-boundary/ErrorContext.tsx, src/shared/error-boundary/index.ts
Add auth gaurd, fix graphql, add error boundaries and login dummy page
=> Feat(auth-gaurd)

src/shared/forminator/inputs/SelectInput.tsx, src/shared/forminator/types.d.ts, src/shared/select/Select.stories.tsx, src/shared/select/Select.tsx, src/shared/select/index.ts
component contains of a form-control w/ input-label and select-input
=> Select w/ form control

src/locales/en/messages.po, src/locales/fa/messages.po, src/shared/error/OverlayError.stories.tsx, src/shared/error/OverlayError.tsx, src/shared/error/index.ts, src/shared/full-page-error/FullPageError.stories.tsx, src/shared/full-page-error/FullPageError.tsx, src/shared/layouts/dashboard-layouts/DashboardLayout.tsx, src/shared/overlay/Overlay.stories.tsx, src/shared/overlay/Overlay.tsx, src/shared/overlay/index.ts
=> chore(error-page): Add proper error page

schema.graphql, src/locales/en/messages.po, src/locales/fa/messages.po, src/pages/projects-page/ProjectForm.tsx, src/pages/projects-page/ProjectsPage.tsx, src/pages/projects-page/deleteProjectReview.mutation.ts
Add delete capability to review-forms
=> feat: Delete reviews

package.json, src/_config/fonts.ts, src/assets/shabnam.css, src/shared/number-output/NumberOutput.stories.tsx, src/shared/number-output/NumberOutput.tsx, src/shared/number-output/index.ts
creates a component which gets a value as prop, shows it with Modern digits when direction is LTR and  Farsi digits when direction is RTL.
=> Number output

src/shared/layouts/dashboard-layouts/menu/NavBarMenuItem.tsx
=> Make navbar links react to hover action

src/core/theme/themes.ts, src/pages/criteria-page/CriteriaForm.tsx, src/pages/strengths-weaknesses-page/StrengthsWeaknessesForm.tsx, src/shared/layouts/dashboard-layouts/menu/NavBarMenuItem.tsx, src/shared/sticky-action-bar/StickyActionBar.stories.tsx
Make primary color, darker, so white text is more readable on it.
=> Update theme ii

src/shared/strengths-weaknesses/ClearIcon.tsx, src/shared/strengths-weaknesses/StrengthsOrWeaknesses.tsx
=> Add remove button to Dominant Characteristics page

src/core/snackbar/Snackbar.stories.tsx, src/core/snackbar/SnackbarProvider.tsx, src/pages/criteria-page/CriteriaPage.tsx, src/pages/projects-page/ProjectsPage.tsx, src/pages/strengths-weaknesses-page/StrengthsWeaknessesPage.tsx, src/shared/snackbar/index.ts, src/shared/snackbar/useBiDiSnackbar.ts
This will add a bi directional Snackbar which will change in case of 'RTL' page direction.
This will also fix an issue which Snackbar would get over the fixed bottom Submit button in forms
=> feat(bi-di-snackbar): add BiDiSnackbar hook

src/shared/progress/CircularProgress.stories.tsx, src/shared/progress/CircularProgress.tsx
A wrapper component which
- receives content as children and place it inside of the material-ui CircularIndicator
- changes its color based on the progress value
=> Circular Indicator

src/shared/progress/CircularProgress.tsx
=> Fix Circular Indicator

src/locales/en/messages.po, src/locales/fa/messages.po, src/pages/criteria-page/CriteriaPage.tsx, src/pages/dashboard-page/DashboardPage.tsx, src/pages/dashboard-page/DashboardPageCircularIndicator.tsx, src/pages/dashboard-page/DominantCharacteristicsCircularIndicator.tsx, src/pages/dashboard-page/PerformanceCompetenciesCircularIndicator.tsx, src/shared/layouts/dashboard-layouts/Brand.tsx, src/shared/layouts/dashboard-layouts/DashboardLayout.tsx
- Clicking on Brand takes the user to the Dashboard page
- Sample progress in Dashboard page
- Circular indicators for dominant characteristics and performance competencies pages
=> Dashboard Page

src/shared/multiline-output/MultilineOutput.stories.tsx, src/shared/multiline-output/MultilineOutput.tsx, src/shared/multiline-output/index.ts
Add component which goes to the next line after '\n' break char
=> Add Multiline Output

src/containers/main/MainContainer.tsx, src/locales/en/messages.po, src/locales/fa/messages.po, src/pages/criteria-page/CriteriaPage.tsx, src/pages/dashboard-page/DashboardPage.tsx, src/pages/guide-page/GuidePage.tsx, src/pages/projects-page/ProjectsPage.tsx, src/pages/strengths-weaknesses-page/StrengthsWeaknessesPage.tsx
- Change name of dashboard page
- Change margin of boxes which wrap pages
=> Minor Ui Fixes

src/pages/projects-page/ProjectsPage.tsx
Now newly added projects are on top.
=> Reverse Projects Order

src/pages/dashboard-page/DominantCharacteristicsCircularIndicator.tsx, src/pages/dashboard-page/PerformanceCompetenciesCircularIndicator.tsx, src/shared/counter/Counter.tsx, src/shared/progress/CircularProgress.tsx
Use the custom progress-indicator instead of mui one, now:
- it has a bg circle
- thicker and larger circle
=> Improve ProgressIndicator of Counter Component

src/shared/counter/Counter.tsx, src/shared/progress/CircularProgress.tsx
- counter turns to yellow when 20 character is remaining
- counter turns to red when remaining character is 0
- add error color to circle-indicator
=> Improve Counter

src/shared/auth/Login.tsx
Fix logo image height issue in lower versions of chrome
=> Fix Logo In The Login Page

src/locales/en/messages.po, src/locales/fa/messages.po, src/pages/manager-review-page/ManagerReviewContent.tsx, src/pages/manager-review-page/ManagerReviewPage.tsx, src/pages/manager-review-page/useCurrentPersonReview.ts, src/pages/manager-review-page/useCurrentProjectReviews.ts, src/shared/project-manager-review/ProjectManagerReview.stories.tsx
implemented CriteriaManagerReview and ProjectManagerReview
=> chore(manager-review-content): complete manager review content

src/AppRouter.tsx, src/containers/main/MainRoutes.tsx, src/pages/self-review-page/SelfReviewPage.tsx
based on
https://github.com/ReactTraining/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md#upgrade-to-react-router-v51
=> chore: make routes v5.1 preferred style

src/pages/criteria-page/CriteriaPage.tsx, src/pages/self-review-page/SelfReviewPage.tsx, src/pages/strengths-weaknesses-page/StrengthsWeaknessesPage.tsx
We did this for compatibility with PEER_REVIEW state
=> criteria and strengths-weakness get reviewee id from props

src/mdx-js__react.d.ts, src/mdx.d.ts, src/pages/criteria-page/CriteriaForm.tsx, src/pages/guide-page/GuideCard.tsx, src/pages/project-comment-page/ProjectCommentPage.tsx, src/pages/projects-page/ProjectsPage.tsx, src/pages/start-review-page/StartReviewCard.tsx, src/pages/strengths-weaknesses-page/StrengthsWeaknessesForm.tsx
=> chore(mdx-js__react): add proper types for MDXContext and everything else

src/locales/en/messages.po, src/locales/fa/messages.po, src/shared/games/games.stories.tsx, src/shared/games/reacteroids/Reacteroids.js, src/shared/games/reacteroids/Ship.ts
- Format code 
- sort imports 
- fix typo
=> sort imports

src/App.tsx, src/containers/main/NavbarUser.tsx, src/relay/RelayEnvironmentContext.tsx, src/relay/index.ts, src/stories/decorators/RelayDecorator.tsx, src/stories/environment.ts
This solves the issue which user would see a stale data (previous user's data logged in) after login.
=> Create a new environment after user logs out

src/shared/auth/LoginForm.tsx
- add autoComplete to inputs
- use box component instead of a br
=> Improve login-page

package.json, yarn.lock
- Upgrade `@material-ui/core`
- Upgrade` @material-ui/icons`
- Upgrade `@material-ui/lab`
=> Upgrade material-ui

package.json, yarn.lock
- Bump `react` from `0.0.0-experimental-241c4467e` to `0.0.0-experimental-aae83a4b9`
- Bump `react-dom` from `0.0.0-experimental-241c4467e` to `0.0.0-experimental-aae83a4b9`
- Bump `@types/react` from `16.9.0` to `16.9.23`
- Bump `@types/react-dom` from `16.9.0` to `16.9.5`
=> Upgrade react

src/shared/forminator/inputs/LimitedTextAreaInput.tsx
=> Clean limited-text-area-input component

package.json, yarn.lock
Install and use `relay-enum-generator` package from `npm`
=> relay-enum-generator

src/pages/result-page/criteria-result-page/CriterionResultRatingGroup.tsx
Include reviewee evaluation and comment in count
=> Fix evaluation/comment count in CriterionResultPage

src/locales/en/messages.po, src/locales/fa/messages.po, src/pages/manager-review-page/ManagerReviewPage.tsx, src/pages/manager-review-page/Username.tsx, src/pages/manager-review-page/performance-competencies/ManagerReviewPerformanceCompetencies.tsx, src/pages/manager-review-page/performance-competencies/ManagerReviewPerformanceCompetenciesDescription.mdx, src/pages/manager-review-page/performance-competencies/ManagerReviewPerformanceCompetenciesExpansionPanel.tsx, src/pages/manager-review-page/performance-competencies/ManagerReviewPerformanceCompetenciesRatingGroup.tsx, src/pages/manager-review-page/performance-competencies/ManagerReviewPerformanceCompetenciesValue.ts, src/pages/manager-review-page/performance-competencies/index.ts
Change Manager review performance competencies layout to match `RESULTS` phase.
=> Manager Review Performance Competencies

package.json, src/App.tsx, src/locales/en/messages.po, src/locales/fa/messages.po, src/pages/manager-review-page/ManagerReviewPrintPage.tsx, yarn.lock
- Add `react-helmet`
- Display reviewee in manager-review print page header
=> Add React Helmet

src/pages/peer-review-page/projectsTab/PeerReviewProjectsTab.tsx, src/pages/peer-review-page/projectsTab/projects-form/PeerReviewProjectsForm.tsx
Buttons must be disabled when there is no change and form is not dirty.
=> Disable peer review achievement submit buttons when they should

schema.graphql, src/containers/main/MainRoutes.tsx, src/containers/main/shouldRenderStartReviewPage.ts, src/core/auth/AuthGuard.tsx, src/locales/en/messages.po, src/locales/fa/messages.po, src/pages/manager-review-dashboard/EvaluationItemOutput.tsx, src/pages/manager-review-dashboard/ItemOutput.tsx, src/pages/manager-review-dashboard/ManagerReviewDashboard.tsx, src/pages/manager-review-dashboard/ManagerReviewDashboardContentItem.tsx, src/pages/manager-review-dashboard/ManagerReviewDashboardDrawerContent.tsx, src/pages/manager-review-dashboard/ManagerReviewDashboardTable.tsx, src/pages/manager-review-dashboard/TableFilters.tsx, src/pages/manager-review-dashboard/useFilters.ts, src/pages/manager-review-dashboard/usePagination.ts, src/pages/manager-review-dashboard/useSortBy.ts, src/shared/evaluation-output/EvaluationOutput.tsx, src/shared/progress/LinearProgress.tsx, src/shared/tab/TabPanel.tsx, src/shared/tab/TabPanels.tsx, src/shared/typography-output/TypographyOutput.tsx, src/shared/typography-output/index.ts
Improve the existing table by adding sort and filters and new fields which can be use to track the status and overall rating. Also clicking on each row will open a drawer which displays more details about each review.
=> Improve manager review dashboard page

src/shared/those-who-did-not-comment/ThoseWhoDidNotComment.tsx
remove ThoseWhoDidNotComment section
=> fix: manager review print page
